#ifndef INPUTMANAGER_H
#define INPUTMANAGER_H

enum EINPUTS
{
	INPUT_LEFT = 0,
	INPUT_RIGHT,
	INPUT_DOWN,
	INPUT_UP,
	INPUT_ATTACK,
	INPUT_JUMP,
	TRANSFORM_GEISHA,
	TRANSFORM_SAMURAI,
	INPUT_NINJACRAWL_UP,
	INPUT_DEBUGAIM,
	INPUT_DEBUGAIM_SPEEDUP,
	INPUT_DEBUGAIM_SPEEDDOWN,
	INPUT_DEBUGAIM_ACCEPT,
	INPUT_SWITCH_DEBUG_TYPE_UP,
	INPUT_SWITCH_DEBUG_TYPE_DOWN,
	INPUT_SCALE_UP_X,
	INPUT_SCALE_DOWN_X,
	INPUT_SCALE_UP_Z,
	INPUT_SCALE_DOWN_Z,
	MAX_INPUTS
};
void InitInputManager();
void UpdateInputManager();
void EndInputManager();
bool GetInput(int nInput);
#endif